version: "3.9"
services:
  
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./html:/usr/share/nginx/html/html
      - ./img:/usr/share/nginx/html/img
      - ./js:/usr/share/nginx/html/js
      - ./style:/usr/share/nginx/html/style
      - ./index.html:/usr/share/nginx/html/index.html
     
      - ./conf/:/etc/nginx/conf.d/:ro
    ports:
      - 80:80
    environment:
      - NGINX_HOST=christedu.ru
    restart: always
    networks:
      docker_cepsite_net:

networks:
  docker_cepsite_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.224.0/24"
